name: Deploy

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write

jobs:
  build-and-upload:
    name: Build and upload
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - build: linux
            os: ubuntu-20.04
            target: x86_64-unknown-linux-gnu

          - build: macos
            os: macos-latest
            target: x86_64-apple-darwin

          - build: windows-gnu
            os: ubuntu-latest
            target: x86_64-pc-windows-gnu

    steps:
      - uses: olegtarasov/get-tag@v2.1.2
        id: get_version

      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - run: |
          sudo apt-get install mingw-w64
        if: matrix.build == 'windows-gnu'

      - run: |
          sudo apt-get install libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libxkbcommon-dev libssl-dev
        if: matrix.build == 'linux'

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Build
        run: |
          cargo build --release --target ${{ matrix.target }}

      - name: Build archive
        shell: bash
        run: |
          binary_name="oklch-color-picker"

          dirname="$binary_name-${{ steps.get_version.outputs.tag }}-${{ matrix.target }}"
          mkdir "$dirname"
          if [ "${{ matrix.build }}" = "windows-gnu" ]; then
            mv "target/${{ matrix.target }}/release/$binary_name.exe" "$dirname"
          else
            mv "target/${{ matrix.target }}/release/$binary_name" "$dirname"
          fi

          if [ "${{ matrix.build }}" = "windows-gnu" ]; then
            zip -r "$dirname.zip" "$dirname"
            echo "ASSET=$dirname.zip" >> $GITHUB_ENV
          else
            tar -czf "$dirname.tar.gz" "$dirname"
            echo "ASSET=$dirname.tar.gz" >> $GITHUB_ENV
          fi

      - name: Upload the binaries
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ env.ASSET }}
